//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointmentreg_overriderate_tbl
    {
        public string empl_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public Nullable<decimal> monthly_cy { get; set; }
        public Nullable<decimal> monthly_ny { get; set; }
        public Nullable<int> step_cy { get; set; }
        public Nullable<int> step_ny { get; set; }
        public Nullable<int> salary_grade { get; set; }
        public string data_status { get; set; }
    }
}
