//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointmentregular_tbl
    {
        public string appt_ctrlno { get; set; }
        public string budget_code { get; set; }
        public string item_no { get; set; }
        public string empl_id { get; set; }
        public string natureappointment_code { get; set; }
        public string prev_appointee_empl_id { get; set; }
        public string who_type { get; set; }
        public string plantilla_page { get; set; }
        public Nullable<bool> contact_int_executive { get; set; }
        public Nullable<bool> contact_int_supervisor { get; set; }
        public Nullable<bool> contact_int_nonsupervisor { get; set; }
        public Nullable<bool> contact_int_staff { get; set; }
        public Nullable<bool> contact_ext_generalpublic { get; set; }
        public Nullable<bool> contact_ext_otheragencies { get; set; }
        public string contact_others { get; set; }
        public Nullable<bool> working_con_office { get; set; }
        public Nullable<bool> working_con_field { get; set; }
        public string working_con_others { get; set; }
        public string approval_status { get; set; }
        public Nullable<bool> posting_status { get; set; }
        public string approval_id { get; set; }
        public string equipment { get; set; }
        public Nullable<bool> supervisory { get; set; }
        public string supervisor_empl_id { get; set; }
        public Nullable<System.DateTime> psb_date { get; set; }
        public string assignment_code { get; set; }
        public string signatory_empl_id { get; set; }
        public string brief_descr_function { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
        public string immediate_sup_empl_id { get; set; }
        public string immediate_next_sup_empl_id { get; set; }
        public string pdf_other_contribution { get; set; }
        public Nullable<System.DateTime> effective_date_sg_ny { get; set; }
        public string employment_status { get; set; }
        public Nullable<bool> reorg_flag { get; set; }
        public string technical_comlvl_code { get; set; }
    }
}
