//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointmentcasual_tbl
    {
        public string appt_ctrlno { get; set; }
        public string budget_code { get; set; }
        public string item_no { get; set; }
        public string empl_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<System.DateTime> period_from { get; set; }
        public Nullable<System.DateTime> period_to { get; set; }
        public string appt_semester { get; set; }
        public string assignment_code { get; set; }
        public string natureappointment_code { get; set; }
        public Nullable<System.DateTime> date_of_assumption { get; set; }
        public string details_remarks { get; set; }
        public string approval_status { get; set; }
        public Nullable<bool> posting_status { get; set; }
        public string approval_id { get; set; }
        public Nullable<System.DateTime> effective_date_sg_ny { get; set; }
    }
}
