//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class benefitsfixed_tbl
    {
        public System.DateTime effective_date { get; set; }
        public string benefits_description { get; set; }
        public Nullable<decimal> benefits_quarterly_allowance { get; set; }
        public Nullable<decimal> benefits_pera { get; set; }
        public Nullable<decimal> clothing_allowance { get; set; }
        public Nullable<decimal> cash_gift { get; set; }
        public Nullable<decimal> productivity_incentives { get; set; }
        public Nullable<decimal> subsistence_daily_rate { get; set; }
        public Nullable<decimal> subsistence_max_amount { get; set; }
        public Nullable<decimal> laundry_daily_rate { get; set; }
        public Nullable<decimal> laundry_max_amount { get; set; }
        public Nullable<decimal> anniversary_bonus { get; set; }
        public Nullable<decimal> honoraria_jo_bonus { get; set; }
    }
}
