//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bth_rcrd_for_resigned_retired_tbl
    {
        public string empl_id { get; set; }
        public System.DateTime effective_date { get; set; }
        public string remakrs { get; set; }
        public string transacton_code { get; set; }
        public string reason_code { get; set; }
        public string created_by { get; set; }
        public string item_no { get; set; }
        public string employment_type { get; set; }
    }
}
