//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate_temp_tbl
    {
        public string user_id { get; set; }
        public string empl_id { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string department_code { get; set; }
        public string certification_text1 { get; set; }
        public string certification_text2 { get; set; }
        public string certification_purpose { get; set; }
        public string certification_issued { get; set; }
    }
}
