//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRIS_HRDEntities : DbContext
    {
        public HRIS_HRDEntities()
            : base("name=HRIS_HRDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empl_jobfunddescr_hdr_tbl> empl_jobfunddescr_hdr_tbl { get; set; }
        public virtual DbSet<vw_empl_jd_pos> vw_empl_jd_pos { get; set; }
        public virtual DbSet<empl_jobfunddescr_dtl_tbl> empl_jobfunddescr_dtl_tbl { get; set; }
        public virtual DbSet<jobfunddescr_task_empl_tbl> jobfunddescr_task_empl_tbl { get; set; }
    
        public virtual ObjectResult<sp_employee_jobfunddescr_hdr_tbl_Result> sp_employee_jobfunddescr_hdr_tbl(string par_applcode, string par_employment_type)
        {
            var par_applcodeParameter = par_applcode != null ?
                new ObjectParameter("par_applcode", par_applcode) :
                new ObjectParameter("par_applcode", typeof(string));
    
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_employee_jobfunddescr_hdr_tbl_Result>("sp_employee_jobfunddescr_hdr_tbl", par_applcodeParameter, par_employment_typeParameter);
        }
    
        public virtual ObjectResult<string> sp_generate_appl_nbr(string p_table_name, Nullable<int> p_charlen, string p_column_name)
        {
            var p_table_nameParameter = p_table_name != null ?
                new ObjectParameter("p_table_name", p_table_name) :
                new ObjectParameter("p_table_name", typeof(string));
    
            var p_charlenParameter = p_charlen.HasValue ?
                new ObjectParameter("p_charlen", p_charlen) :
                new ObjectParameter("p_charlen", typeof(int));
    
            var p_column_nameParameter = p_column_name != null ?
                new ObjectParameter("P_column_name", p_column_name) :
                new ObjectParameter("P_column_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_generate_appl_nbr", p_table_nameParameter, p_charlenParameter, p_column_nameParameter);
        }
    
        public virtual ObjectResult<string> sp_generate_jobfunction_hdr_key_code(string par_department_code, string par_position_code)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_position_codeParameter = par_position_code != null ?
                new ObjectParameter("par_position_code", par_position_code) :
                new ObjectParameter("par_position_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_generate_jobfunction_hdr_key_code", par_department_codeParameter, par_position_codeParameter);
        }
    
        public virtual ObjectResult<string> sp_generate_key_jobfunc_dtl(string par_department_code, string par_position_code, string par_fjd_keycode)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_position_codeParameter = par_position_code != null ?
                new ObjectParameter("par_position_code", par_position_code) :
                new ObjectParameter("par_position_code", typeof(string));
    
            var par_fjd_keycodeParameter = par_fjd_keycode != null ?
                new ObjectParameter("par_fjd_keycode", par_fjd_keycode) :
                new ObjectParameter("par_fjd_keycode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_generate_key_jobfunc_dtl", par_department_codeParameter, par_position_codeParameter, par_fjd_keycodeParameter);
        }
    
        public virtual ObjectResult<sp_get_employeemaster_information_hrd_Result> sp_get_employeemaster_information_hrd(string par_empl_id)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_employeemaster_information_hrd_Result>("sp_get_employeemaster_information_hrd", par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_jobfdn_employee_combo_list_Result> sp_jobfdn_employee_combo_list(string par_budget_code, string par_department_code, string par_divion_code, string par_section_code)
        {
            var par_budget_codeParameter = par_budget_code != null ?
                new ObjectParameter("par_budget_code", par_budget_code) :
                new ObjectParameter("par_budget_code", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_divion_codeParameter = par_divion_code != null ?
                new ObjectParameter("par_divion_code", par_divion_code) :
                new ObjectParameter("par_divion_code", typeof(string));
    
            var par_section_codeParameter = par_section_code != null ?
                new ObjectParameter("par_section_code", par_section_code) :
                new ObjectParameter("par_section_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_jobfdn_employee_combo_list_Result>("sp_jobfdn_employee_combo_list", par_budget_codeParameter, par_department_codeParameter, par_divion_codeParameter, par_section_codeParameter);
        }
    
        public virtual ObjectResult<string> sp_validate_employee_jobfunc_hdr_tbl(string par_applcode, string par_department_code, string par_division_code, string par_section_code, string par_position_code, string par_budget_year, string par_empl_id, string par_action)
        {
            var par_applcodeParameter = par_applcode != null ?
                new ObjectParameter("par_applcode", par_applcode) :
                new ObjectParameter("par_applcode", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_division_codeParameter = par_division_code != null ?
                new ObjectParameter("par_division_code", par_division_code) :
                new ObjectParameter("par_division_code", typeof(string));
    
            var par_section_codeParameter = par_section_code != null ?
                new ObjectParameter("par_section_code", par_section_code) :
                new ObjectParameter("par_section_code", typeof(string));
    
            var par_position_codeParameter = par_position_code != null ?
                new ObjectParameter("par_position_code", par_position_code) :
                new ObjectParameter("par_position_code", typeof(string));
    
            var par_budget_yearParameter = par_budget_year != null ?
                new ObjectParameter("par_budget_year", par_budget_year) :
                new ObjectParameter("par_budget_year", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_actionParameter = par_action != null ?
                new ObjectParameter("par_action", par_action) :
                new ObjectParameter("par_action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_validate_employee_jobfunc_hdr_tbl", par_applcodeParameter, par_department_codeParameter, par_division_codeParameter, par_section_codeParameter, par_position_codeParameter, par_budget_yearParameter, par_empl_idParameter, par_actionParameter);
        }
    
        public virtual ObjectResult<string> sp_validate_jobfunc_hdr_tbl(string par_department_code, string par_division_code, string par_section_code, string par_position_code)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_division_codeParameter = par_division_code != null ?
                new ObjectParameter("par_division_code", par_division_code) :
                new ObjectParameter("par_division_code", typeof(string));
    
            var par_section_codeParameter = par_section_code != null ?
                new ObjectParameter("par_section_code", par_section_code) :
                new ObjectParameter("par_section_code", typeof(string));
    
            var par_position_codeParameter = par_position_code != null ?
                new ObjectParameter("par_position_code", par_position_code) :
                new ObjectParameter("par_position_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_validate_jobfunc_hdr_tbl", par_department_codeParameter, par_division_codeParameter, par_section_codeParameter, par_position_codeParameter);
        }
    
        public virtual ObjectResult<sp_department_trans_list_Result> sp_department_trans_list(string par_transaction_code, string par_empl_id)
        {
            var par_transaction_codeParameter = par_transaction_code != null ?
                new ObjectParameter("par_transaction_code", par_transaction_code) :
                new ObjectParameter("par_transaction_code", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_department_trans_list_Result>("sp_department_trans_list", par_transaction_codeParameter, par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_get_common_jobfunddescr_list_Result> sp_get_common_jobfunddescr_list(string par_department_code, string par_division_code, string par_section_code, string par_position_code, string par_applcode, string par_empl_id)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_division_codeParameter = par_division_code != null ?
                new ObjectParameter("par_division_code", par_division_code) :
                new ObjectParameter("par_division_code", typeof(string));
    
            var par_section_codeParameter = par_section_code != null ?
                new ObjectParameter("par_section_code", par_section_code) :
                new ObjectParameter("par_section_code", typeof(string));
    
            var par_position_codeParameter = par_position_code != null ?
                new ObjectParameter("par_position_code", par_position_code) :
                new ObjectParameter("par_position_code", typeof(string));
    
            var par_applcodeParameter = par_applcode != null ?
                new ObjectParameter("par_applcode", par_applcode) :
                new ObjectParameter("par_applcode", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_common_jobfunddescr_list_Result>("sp_get_common_jobfunddescr_list", par_department_codeParameter, par_division_codeParameter, par_section_codeParameter, par_position_codeParameter, par_applcodeParameter, par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_validate_empl_job_percentage_Result> sp_validate_empl_job_percentage(string par_applcode)
        {
            var par_applcodeParameter = par_applcode != null ?
                new ObjectParameter("par_applcode", par_applcode) :
                new ObjectParameter("par_applcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_validate_empl_job_percentage_Result>("sp_validate_empl_job_percentage", par_applcodeParameter);
        }
    
        public virtual ObjectResult<string> sp_add_to_common(string par_fjd_code, string par_empl_ctrl_nbr)
        {
            var par_fjd_codeParameter = par_fjd_code != null ?
                new ObjectParameter("par_fjd_code", par_fjd_code) :
                new ObjectParameter("par_fjd_code", typeof(string));
    
            var par_empl_ctrl_nbrParameter = par_empl_ctrl_nbr != null ?
                new ObjectParameter("par_empl_ctrl_nbr", par_empl_ctrl_nbr) :
                new ObjectParameter("par_empl_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_add_to_common", par_fjd_codeParameter, par_empl_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_employee_jobfun_approval_list_Result> sp_employee_jobfun_approval_list(string par_employment_type, string par_department_code, string par_division_code, string par_section_code, string par_user_id, string par_approve_only)
        {
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_division_codeParameter = par_division_code != null ?
                new ObjectParameter("par_division_code", par_division_code) :
                new ObjectParameter("par_division_code", typeof(string));
    
            var par_section_codeParameter = par_section_code != null ?
                new ObjectParameter("par_section_code", par_section_code) :
                new ObjectParameter("par_section_code", typeof(string));
    
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            var par_approve_onlyParameter = par_approve_only != null ?
                new ObjectParameter("par_approve_only", par_approve_only) :
                new ObjectParameter("par_approve_only", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_employee_jobfun_approval_list_Result>("sp_employee_jobfun_approval_list", par_employment_typeParameter, par_department_codeParameter, par_division_codeParameter, par_section_codeParameter, par_user_idParameter, par_approve_onlyParameter);
        }
    
        public virtual ObjectResult<sp_employee_list_with_masterdata_list_hrd_Result> sp_employee_list_with_masterdata_list_hrd(string par_employment_type, string par_department_code, string par_division_code, string par_section_code, string par_empl_id)
        {
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_division_codeParameter = par_division_code != null ?
                new ObjectParameter("par_division_code", par_division_code) :
                new ObjectParameter("par_division_code", typeof(string));
    
            var par_section_codeParameter = par_section_code != null ?
                new ObjectParameter("par_section_code", par_section_code) :
                new ObjectParameter("par_section_code", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_employee_list_with_masterdata_list_hrd_Result>("sp_employee_list_with_masterdata_list_hrd", par_employment_typeParameter, par_department_codeParameter, par_division_codeParameter, par_section_codeParameter, par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_employee_jobfunddescr_dtl_tbl_list_Result> sp_employee_jobfunddescr_dtl_tbl_list(string par_empl_id, string par_empl_status, string par_position_code)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_empl_statusParameter = par_empl_status != null ?
                new ObjectParameter("par_empl_status", par_empl_status) :
                new ObjectParameter("par_empl_status", typeof(string));
    
            var par_position_codeParameter = par_position_code != null ?
                new ObjectParameter("par_position_code", par_position_code) :
                new ObjectParameter("par_position_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_employee_jobfunddescr_dtl_tbl_list_Result>("sp_employee_jobfunddescr_dtl_tbl_list", par_empl_idParameter, par_empl_statusParameter, par_position_codeParameter);
        }
    
        public virtual ObjectResult<sp_approval_status_hrd_Result> sp_approval_status_hrd(string par_position_code, string par_empl_id)
        {
            var par_position_codeParameter = par_position_code != null ?
                new ObjectParameter("par_position_code", par_position_code) :
                new ObjectParameter("par_position_code", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_approval_status_hrd_Result>("sp_approval_status_hrd", par_position_codeParameter, par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_common_task_per_jobdescription_add_list_Result> sp_common_task_per_jobdescription_add_list(string par_fjd_code, string par_empl_id)
        {
            var par_fjd_codeParameter = par_fjd_code != null ?
                new ObjectParameter("par_fjd_code", par_fjd_code) :
                new ObjectParameter("par_fjd_code", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_common_task_per_jobdescription_add_list_Result>("sp_common_task_per_jobdescription_add_list", par_fjd_codeParameter, par_empl_idParameter);
        }
    
        public virtual ObjectResult<string> sp_generate_appl_nbr_task(string p_table_name, Nullable<int> p_charlen, string p_column_name)
        {
            var p_table_nameParameter = p_table_name != null ?
                new ObjectParameter("p_table_name", p_table_name) :
                new ObjectParameter("p_table_name", typeof(string));
    
            var p_charlenParameter = p_charlen.HasValue ?
                new ObjectParameter("p_charlen", p_charlen) :
                new ObjectParameter("p_charlen", typeof(int));
    
            var p_column_nameParameter = p_column_name != null ?
                new ObjectParameter("P_column_name", p_column_name) :
                new ObjectParameter("P_column_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_generate_appl_nbr_task", p_table_nameParameter, p_charlenParameter, p_column_nameParameter);
        }
    
        public virtual ObjectResult<sp_jobdescription_task_empl_tbl_list_Result> sp_jobdescription_task_empl_tbl_list(string par_fjd_code, string par_add_mode, string par_empl_id)
        {
            var par_fjd_codeParameter = par_fjd_code != null ?
                new ObjectParameter("par_fjd_code", par_fjd_code) :
                new ObjectParameter("par_fjd_code", typeof(string));
    
            var par_add_modeParameter = par_add_mode != null ?
                new ObjectParameter("par_add_mode", par_add_mode) :
                new ObjectParameter("par_add_mode", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_jobdescription_task_empl_tbl_list_Result>("sp_jobdescription_task_empl_tbl_list", par_fjd_codeParameter, par_add_modeParameter, par_empl_idParameter);
        }
    }
}
