//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class communicationmemo_tbl
    {
        public string empl_id { get; set; }
        public string memo_descr { get; set; }
        public Nullable<decimal> comm_amount { get; set; }
        public string recrd_status { get; set; }
    }
}
