//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class competencylevel_tbl
    {
        public string comlvl_code { get; set; }
        public string comlvl_short_descr { get; set; }
        public string comlvl_descr { get; set; }
    }
}
