//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_tracking_nbrs_tbl
    {
        public string doc_ctrl_nbr { get; set; }
        public string doc_fund_subcode { get; set; }
        public string doc_obr_nbr { get; set; }
        public string doc_voucher_nbr { get; set; }
        public string doc_check_nbr { get; set; }
        public string doc_othr_info { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_user_id { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_user_id { get; set; }
    }
}
