//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_route_funds_tbl
    {
        public System.DateTime effective_date { get; set; }
        public int route_ctrl_nbr { get; set; }
        public string fund_code { get; set; }
    }
}
