//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empl_jobfunddescr_dtl_tbl
    {
        public string empl_ctrl_nbr { get; set; }
        public string fjd_code { get; set; }
        public string fjd_descr { get; set; }
        public Nullable<bool> fjd_flag { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<decimal> fjd_percent_weight { get; set; }
        public string fjd_type { get; set; }
        public string fjd_orig_added { get; set; }
    }
}
