//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeesloyaltybonus_tbl
    {
        public string budget_code { get; set; }
        public string empl_id { get; set; }
        public string employment_type { get; set; }
        public Nullable<int> years_of_tenure { get; set; }
        public Nullable<System.DateTime> loyalty_effectivity_date { get; set; }
    }
}
