//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erasure_alteration_hdr_tbl
    {
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string erasure_alteration_ctrl_no { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> date_of_erasure_alteration { get; set; }
    }
}
