//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erasure_alteration_dtl_tbl
    {
        public int erasure_alteration_seq_no { get; set; }
        public string erasure_alteration_ctrl_no { get; set; }
        public string erasure_alteration_descr { get; set; }
        public string erasure_alteration_from { get; set; }
        public string erasure_alteration_to { get; set; }
    }
}
