//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erspinstallation_tbl
    {
        public string budget_code { get; set; }
        public string appt1_series_nbr_ce { get; set; }
        public string appt1_series_year_ce { get; set; }
        public string appt2_series_nbr_ce { get; set; }
        public string appt2_series_year_ce { get; set; }
        public string pdf_pres_approp_act { get; set; }
        public string pdf_prev_approp_act { get; set; }
    }
}
