//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class excludeappointment_tbl
    {
        public string budget_code { get; set; }
        public string budget_code_target { get; set; }
        public string department_code { get; set; }
        public string appt_semester { get; set; }
        public string employment_type { get; set; }
        public string empl_id { get; set; }
    }
}
