//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gsis_upd_payroll_tbl
    {
        public int id { get; set; }
        public string uploaded_year { get; set; }
        public string uploaded_month { get; set; }
        public string uploaded_by_user { get; set; }
        public Nullable<System.DateTime> uploaded_datetime { get; set; }
        public string gsis_bpno { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string prefix_name { get; set; }
        public string appellation { get; set; }
        public string birth_date { get; set; }
        public string gsis_crn { get; set; }
        public Nullable<decimal> monthly_salary { get; set; }
        public string effectivity_date { get; set; }
        public Nullable<decimal> gsis_ps { get; set; }
        public Nullable<decimal> gsis_gs { get; set; }
        public Nullable<decimal> sif_gs { get; set; }
        public Nullable<decimal> gsis_conso_ln { get; set; }
        public Nullable<decimal> gsis_ecard_ln { get; set; }
        public Nullable<decimal> salary_loan { get; set; }
        public Nullable<decimal> cash_adv { get; set; }
        public Nullable<decimal> gsis_emergency_ln { get; set; }
        public Nullable<decimal> gsis_educ_asst_ln { get; set; }
        public Nullable<decimal> ela { get; set; }
        public Nullable<decimal> gsis_sos_ln { get; set; }
        public Nullable<decimal> gsis_policy_reg_ln { get; set; }
        public Nullable<decimal> gsis_policy_opt_ln { get; set; }
        public Nullable<decimal> gsis_real_state_ln { get; set; }
        public Nullable<decimal> lch_dcs { get; set; }
        public Nullable<decimal> stock_purchase { get; set; }
        public Nullable<decimal> gsis_uoli { get; set; }
        public Nullable<decimal> ceap { get; set; }
        public Nullable<decimal> edu_child { get; set; }
        public Nullable<decimal> genesis { get; set; }
        public Nullable<decimal> genplus { get; set; }
        public Nullable<decimal> genflexi { get; set; }
        public Nullable<decimal> genspcl { get; set; }
        public Nullable<decimal> gsis_help { get; set; }
        public Nullable<decimal> gfal { get; set; }
        public Nullable<decimal> mpl { get; set; }
        public Nullable<decimal> cpl { get; set; }
        public Nullable<decimal> gel { get; set; }
        public string rcrd_status { get; set; }
    }
}
