//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gsis_upd_payroll_hdr_tbl
    {
        public int id { get; set; }
        public string uploaded_year { get; set; }
        public string uploaded_month { get; set; }
        public string uploaded_by_user { get; set; }
        public Nullable<System.DateTime> uploaded_datetime { get; set; }
        public string gsis_bpno { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string prefix_name { get; set; }
        public string appellation { get; set; }
        public string birth_date { get; set; }
        public string gsis_crn { get; set; }
        public Nullable<decimal> monthly_salary { get; set; }
        public string effectivity_date { get; set; }
        public string rcrd_status { get; set; }
    }
}
