//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gsis_upd_payroll_dtl_tbl
    {
        public int id { get; set; }
        public string uploaded_year { get; set; }
        public string uploaded_month { get; set; }
        public string gsis_bpno { get; set; }
        public string deduc_code { get; set; }
        public Nullable<decimal> deduc_amt { get; set; }
        public string rcrd_status { get; set; }
    }
}
