//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hazardpays_tbl
    {
        public System.DateTime effective_date { get; set; }
        public string salary_grade { get; set; }
        public Nullable<decimal> hp_percentage { get; set; }
    }
}
