//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class holidays_tbl
    {
        public System.DateTime holiday_date { get; set; }
        public string holiday_name { get; set; }
        public string holiday_type { get; set; }
        public Nullable<bool> with_pay_regular { get; set; }
        public Nullable<bool> with_pay_casual { get; set; }
        public Nullable<bool> with_pay_joborder { get; set; }
    }
}
