//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jo_tax_tbl
    {
        public string bir_class { get; set; }
        public System.DateTime effective_date { get; set; }
        public string bir_class_descr { get; set; }
        public Nullable<decimal> lower_limit { get; set; }
        public Nullable<decimal> upper_limit { get; set; }
        public Nullable<double> wi_sworn_perc { get; set; }
        public Nullable<double> wo_sworn_perc { get; set; }
        public Nullable<double> tax_perc { get; set; }
        public Nullable<double> vat_perc { get; set; }
    }
}
