//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobfunddescr_task_empl_tbl
    {
        public string task_ctrl_nbr { get; set; }
        public string fjd_code { get; set; }
        public string empl_id { get; set; }
        public string task_descr { get; set; }
        public string task_add_mode { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by { get; set; }
    }
}
