//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nosa_tbl
    {
        public string nosa_year { get; set; }
        public string nosa_month { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public Nullable<decimal> salary_amount { get; set; }
        public string salary_type { get; set; }
    }
}
