//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class othrpayamt_tbl
    {
        public string payrolltemplate_code { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string empl_id { get; set; }
        public Nullable<decimal> oth_amount1 { get; set; }
        public Nullable<decimal> oth_amount2 { get; set; }
        public Nullable<decimal> oth_amount3 { get; set; }
        public Nullable<decimal> oth_amount4 { get; set; }
        public Nullable<decimal> oth_amount5 { get; set; }
    }
}
