//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class othrpaysetup_tbl
    {
        public string payrolltemplate_code { get; set; }
        public string fld1_descr { get; set; }
        public string fld2_descr { get; set; }
        public string fld3_descr { get; set; }
        public string fld4_descr { get; set; }
        public string fld5_descr { get; set; }
        public string fld1_type { get; set; }
        public string fld2_type { get; set; }
        public string fld3_type { get; set; }
        public string fld4_type { get; set; }
        public string fld5_type { get; set; }
        public Nullable<decimal> fld1_fixed_amt { get; set; }
        public Nullable<decimal> fld2_fixed_amt { get; set; }
        public Nullable<decimal> fld3_fixed_amt { get; set; }
        public Nullable<decimal> fld4_fixed_amt { get; set; }
        public Nullable<decimal> fld5_fixed_amt { get; set; }
        public string account_code { get; set; }
        public string account_sub_code { get; set; }
        public string gn_taxable { get; set; }
    }
}
