//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistryledger_tbl
    {
        public string payroll_year { get; set; }
        public string employment_type { get; set; }
        public string payrolltemplate_code { get; set; }
        public Nullable<int> control_seq_no { get; set; }
        public Nullable<int> max_control_seq_no { get; set; }
        public string related_template_no1 { get; set; }
        public string related_template_no2 { get; set; }
        public string related_template_no3 { get; set; }
        public string related_template_no4 { get; set; }
        public string related_template_no5 { get; set; }
        public string related_template_no6 { get; set; }
        public string related_template_no7 { get; set; }
        public string related_template_no8 { get; set; }
        public string related_template_no9 { get; set; }
        public string related_template_no10 { get; set; }
    }
}
