//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollemployeegroupings_dtl_tbl
    {
        public string payroll_group_nbr { get; set; }
        public string empl_id { get; set; }
        public Nullable<bool> emp_status { get; set; }
    }
}
