//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistry_dtl_othded_tbl
    {
        public string payrolltemplate_code { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string empl_id { get; set; }
        public Nullable<decimal> other_ded_mand1 { get; set; }
        public Nullable<decimal> other_ded_mand2 { get; set; }
        public Nullable<decimal> other_ded_mand3 { get; set; }
        public Nullable<decimal> other_ded_mand4 { get; set; }
        public Nullable<decimal> other_ded_mand5 { get; set; }
        public Nullable<decimal> other_ded_mand6 { get; set; }
        public Nullable<decimal> other_ded_mand7 { get; set; }
        public Nullable<decimal> other_ded_mand8 { get; set; }
        public Nullable<decimal> other_ded_mand9 { get; set; }
        public Nullable<decimal> other_ded_mand10 { get; set; }
        public Nullable<decimal> other_ded_prem1 { get; set; }
        public Nullable<decimal> other_ded_prem2 { get; set; }
        public Nullable<decimal> other_ded_prem3 { get; set; }
        public Nullable<decimal> other_ded_prem4 { get; set; }
        public Nullable<decimal> other_ded_prem5 { get; set; }
        public Nullable<decimal> other_ded_prem6 { get; set; }
        public Nullable<decimal> other_ded_prem7 { get; set; }
        public Nullable<decimal> other_ded_prem8 { get; set; }
        public Nullable<decimal> other_ded_prem9 { get; set; }
        public Nullable<decimal> other_ded_prem10 { get; set; }
        public Nullable<decimal> other_ded_loan1 { get; set; }
        public Nullable<decimal> other_ded_loan2 { get; set; }
        public Nullable<decimal> other_ded_loan3 { get; set; }
        public Nullable<decimal> other_ded_loan4 { get; set; }
        public Nullable<decimal> other_ded_loan5 { get; set; }
        public Nullable<decimal> other_ded_loan6 { get; set; }
        public Nullable<decimal> other_ded_loan7 { get; set; }
        public Nullable<decimal> other_ded_loan8 { get; set; }
        public Nullable<decimal> other_ded_loan9 { get; set; }
        public Nullable<decimal> other_ded_loan10 { get; set; }
        public string seq_no { get; set; }
    }
}
