//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_bac_info_tbl
    {
        public System.DateTime effective_date { get; set; }
        public string empl_id { get; set; }
        public string bac_position_descr { get; set; }
        public string bac_position_class { get; set; }
        public Nullable<decimal> bac_allowance_amt { get; set; }
        public Nullable<bool> rcrd_status { get; set; }
    }
}
