//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistry_dtl_ovtm_brkdwn_tbl
    {
        public string payroll_registry_nbr { get; set; }
        public string empl_id { get; set; }
        public System.DateTime ot_date { get; set; }
        public Nullable<decimal> hours_rendered { get; set; }
        public Nullable<decimal> ot_perc { get; set; }
    }
}
