//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistry_hdr_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string payrolltemplate_code { get; set; }
        public string payroll_group_nbr { get; set; }
        public string payroll_registry_descr { get; set; }
        public Nullable<System.DateTime> payroll_period_from { get; set; }
        public Nullable<System.DateTime> payroll_period_to { get; set; }
        public Nullable<double> nod_work_1st { get; set; }
        public Nullable<double> nod_work_2nd { get; set; }
        public string post_status { get; set; }
        public Nullable<System.DateTime> payroll_dttm_created { get; set; }
        public Nullable<System.DateTime> payroll_dttm_updated { get; set; }
        public string user_id_created_by { get; set; }
        public string user_id_updated_by { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public string payment_mode { get; set; }
        public string department_code { get; set; }
        public string function_code { get; set; }
        public string allotment_code { get; set; }
    }
}
