//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollmapping_tbl
    {
        public string payrolltemplate_code { get; set; }
        public string account_code { get; set; }
        public string account_sub_code { get; set; }
        public string group_code { get; set; }
        public Nullable<int> report_column_order { get; set; }
        public string reference_table { get; set; }
        public string reference_field { get; set; }
        public string related_acct_code { get; set; }
    }
}
