//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollinstallation_tbl
    {
        public string payroll_year { get; set; }
        public string employment_type { get; set; }
        public System.DateTime effective_date { get; set; }
        public Nullable<int> pera_days_conv { get; set; }
        public Nullable<int> monthly_salary_days_conv { get; set; }
        public Nullable<int> monthly_ot_days_conv { get; set; }
        public Nullable<int> hours_in_1day_conv { get; set; }
        public Nullable<decimal> minimum_net_pay { get; set; }
        public Nullable<double> mone_constant_factor { get; set; }
    }
}
