//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistry_hdr_rls_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_registry_nbr { get; set; }
        public System.DateTime released_dttm { get; set; }
        public string department_code { get; set; }
        public string remarks { get; set; }
        public string user_id_released_by { get; set; }
        public string user_id_returned_by { get; set; }
        public string user_id_void_by { get; set; }
        public Nullable<System.DateTime> returned_dttm { get; set; }
        public Nullable<System.DateTime> void_dttm { get; set; }
    }
}
