//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollaccounts_tbl
    {
        public string account_code { get; set; }
        public string account_title { get; set; }
        public string account_short_title { get; set; }
        public string nature_of_account { get; set; }
        public string acctclass_code { get; set; }
        public string accttype_code { get; set; }
    }
}
