//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistry_dtl_phic_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string empl_id { get; set; }
        public Nullable<decimal> empl_no_share { get; set; }
        public Nullable<decimal> gross_pay { get; set; }
        public Nullable<decimal> net_pay { get; set; }
        public Nullable<decimal> wtax_perc { get; set; }
        public Nullable<decimal> wtax { get; set; }
        public Nullable<decimal> btax_perc { get; set; }
        public Nullable<decimal> btax { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<decimal> wtax_2perc { get; set; }
        public Nullable<decimal> wtax_3perc { get; set; }
        public Nullable<decimal> wtax_5perc { get; set; }
        public Nullable<decimal> wtax_8perc { get; set; }
        public Nullable<decimal> wtax_10perc { get; set; }
        public Nullable<decimal> wtax_15perc { get; set; }
    }
}
