//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollemployee_tax_tbl
    {
        public string empl_id { get; set; }
        public System.DateTime effective_date { get; set; }
        public string bir_class { get; set; }
        public Nullable<bool> with_sworn { get; set; }
        public Nullable<bool> fixed_rate { get; set; }
        public Nullable<decimal> total_gross_pay { get; set; }
        public Nullable<bool> dedct_status { get; set; }
        public string rcrd_status { get; set; }
        public string user_id_created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string user_id_updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public Nullable<decimal> w_tax_perc { get; set; }
        public Nullable<decimal> bus_tax_perc { get; set; }
        public Nullable<decimal> vat_perc { get; set; }
        public Nullable<decimal> exmpt_amt { get; set; }
    }
}
