//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollemployeegroupings_hdr_tbl
    {
        public string payroll_group_nbr { get; set; }
        public string employment_type { get; set; }
        public string grouping_descr { get; set; }
        public string department_code { get; set; }
        public string sub_department_code { get; set; }
        public string division_code { get; set; }
        public string section_code { get; set; }
        public string fund_code { get; set; }
        public string function_code { get; set; }
        public string special_group { get; set; }
        public string charge_to { get; set; }
        public string sig_name { get; set; }
        public string sig_designation { get; set; }
        public Nullable<System.DateTime> dttm_created { get; set; }
        public Nullable<System.DateTime> dttm_updated { get; set; }
        public string created_by_user { get; set; }
        public string updated_by_user { get; set; }
        public string sig_name2 { get; set; }
        public string sig_designation2 { get; set; }
    }
}
