//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollcertification_tbl
    {
        public string payrolltemplate_code { get; set; }
        public string sig1_certification { get; set; }
        public string sig2_certification { get; set; }
        public string sig3_certification { get; set; }
        public string sig4_certification { get; set; }
        public string sig1_name_override { get; set; }
        public string sig2_name_override { get; set; }
        public string sig3_name_override { get; set; }
        public string sig4_name_override { get; set; }
        public string sig1_position_override { get; set; }
        public string sig2_position_override { get; set; }
        public string sig3_position_override { get; set; }
        public string sig4_position_override { get; set; }
    }
}
