//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrolldeduc_ledger_upd_tbl
    {
        public string empl_id { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string deduc_code { get; set; }
        public string deduc_seq { get; set; }
        public Nullable<decimal> uploaded_amount { get; set; }
        public string uploaded_status { get; set; }
        public string uploaded_by_user { get; set; }
        public Nullable<System.DateTime> uploaded_dttm { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
