//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistry_dtl_jo_void_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string empl_id { get; set; }
        public string rate_basis { get; set; }
        public Nullable<double> days_worked { get; set; }
        public Nullable<double> hours_worked { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> daily_rate { get; set; }
        public Nullable<decimal> hourly_rate { get; set; }
        public Nullable<decimal> gross_pay { get; set; }
        public Nullable<decimal> net_pay { get; set; }
        public Nullable<double> lates_mins_hrs { get; set; }
        public Nullable<decimal> lates_mh_amount { get; set; }
        public Nullable<decimal> hdmf_gs { get; set; }
        public Nullable<decimal> hdmf_ps { get; set; }
        public Nullable<decimal> phic_gs { get; set; }
        public Nullable<decimal> phic_ps { get; set; }
        public Nullable<decimal> wtax_2perc { get; set; }
        public Nullable<decimal> wtax_3perc { get; set; }
        public Nullable<decimal> wtax_5perc { get; set; }
        public Nullable<decimal> wtax_8perc { get; set; }
        public Nullable<decimal> wtax_10perc { get; set; }
        public Nullable<decimal> wtax_15perc { get; set; }
        public Nullable<decimal> sss_ps { get; set; }
        public Nullable<decimal> hdmf_ps2 { get; set; }
        public Nullable<decimal> hdmf_mp2 { get; set; }
        public Nullable<decimal> philamlife_ps { get; set; }
        public Nullable<decimal> uniform_amt { get; set; }
        public Nullable<decimal> other_premium1 { get; set; }
        public Nullable<decimal> other_premium2 { get; set; }
        public Nullable<decimal> other_premium3 { get; set; }
        public Nullable<decimal> hdmf_mpl_ln { get; set; }
        public Nullable<decimal> hdmf_hse_ln { get; set; }
        public Nullable<decimal> hdmf_cal_ln { get; set; }
        public Nullable<decimal> hdmf_loyalty_card { get; set; }
        public Nullable<decimal> nico_ln { get; set; }
        public Nullable<decimal> network_ln { get; set; }
        public Nullable<decimal> ccmpc_ln { get; set; }
        public Nullable<decimal> other_loan1 { get; set; }
        public Nullable<decimal> other_loan2 { get; set; }
        public Nullable<decimal> other_loan3 { get; set; }
        public string post_status { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public string voucher_nbr { get; set; }
        public string created_by_user { get; set; }
        public string updated_by_user { get; set; }
        public string posted_by_user { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public Nullable<decimal> nbr_days_absent { get; set; }
    }
}
