//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbb_tbl
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public double amount1 { get; set; }
        public double amount2 { get; set; }
    }
}
