//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_contact_id_tbl
    {
        public string empl_id { get; set; }
        public string gsis_id_no { get; set; }
        public string hdmf_id_no { get; set; }
        public string phic_id_no { get; set; }
        public string sss_id_no { get; set; }
        public string tel_no { get; set; }
        public string mobile_no { get; set; }
        public string email_add { get; set; }
        public string blood_type { get; set; }
        public string gsis_bp_id_no { get; set; }
        public string bir_tin { get; set; }
    }
}
