//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnelnamescs_aud
    {
        public System.DateTime effective_date { get; set; }
        public string empl_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix_name { get; set; }
        public string civil_status { get; set; }
        public string old_civil_status { get; set; }
        public string gender { get; set; }
        public string old_gender { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<System.DateTime> old_birth_date { get; set; }
        public string user_id_creator { get; set; }
        public Nullable<System.DateTime> created_ddtm { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<System.DateTime> updated_ddtm { get; set; }
        public string courtisy_title { get; set; }
        public string postfix_name { get; set; }
    }
}
