//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_csceligibilty_tbl
    {
        public int seq_no { get; set; }
        public string empl_id { get; set; }
        public string cscsrvc_ra1080 { get; set; }
        public string rating { get; set; }
        public string examination_date { get; set; }
        public string examination_place { get; set; }
        public string number { get; set; }
        public string validity_date { get; set; }
        public string csc_type_code { get; set; }
    }
}
