//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_ao_tbl
    {
        public string empl_id { get; set; }
        public System.DateTime effective_date { get; set; }
        public string department_code { get; set; }
        public string subdepartment_code { get; set; }
        public string division_code { get; set; }
        public string section_code { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
