//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phic_share_add_empl_tbl
    {
        public string empl_id { get; set; }
        public string group_code { get; set; }
        public string position_long_title { get; set; }
        public Nullable<bool> rcrd_status { get; set; }
        public Nullable<decimal> rate_amount { get; set; }
        public string employee_name { get; set; }
        public string empl_type { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> creted_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
