//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phic_cert_tbl
    {
        public string department_code { get; set; }
        public string cert_descr { get; set; }
        public string sig1_name { get; set; }
        public string sig1_position { get; set; }
        public string sig2_name { get; set; }
        public string sig2_position { get; set; }
        public string sig3_name { get; set; }
        public string sig3_position { get; set; }
    }
}
