//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phic_refund
    {
        public string empl_id { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public Nullable<decimal> stq { get; set; }
        public Nullable<decimal> ndq { get; set; }
        public decimal rdq { get; set; }
        public double total_amt { get; set; }
    }
}
