//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phic_1perc_diff_tbl
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public int payroll_month { get; set; }
        public string monthly_payroll_gsis { get; set; }
        public string deduct_gsis_payroll { get; set; }
        public double phic_gs_deduct_3perc { get; set; }
        public double phic_ps_deduct_3perc { get; set; }
        public string phic_gs_4perc { get; set; }
        public string phic_ps_4perc { get; set; }
        public decimal phic_gs_diff_1perc { get; set; }
        public decimal phic_ps_diff_1perc { get; set; }
        public string REMARKS { get; set; }
    }
}
