//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phic_share_groupings_tbl
    {
        public string group_code { get; set; }
        public string group_description { get; set; }
        public string employment_type { get; set; }
        public string group_class { get; set; }
    }
}
