//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phic_share_ledger_dtl_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string department_code { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string ledger_status { get; set; }
    }
}
