//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class philhealth_tbl
    {
        public System.DateTime effective_date { get; set; }
        public Nullable<decimal> salary_flooring_amt { get; set; }
        public Nullable<decimal> salary_ceiling_amt { get; set; }
        public Nullable<decimal> contribution_rate { get; set; }
        public string philhealth_remarks { get; set; }
    }
}
