//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla_exc_3months_tbl
    {
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string empl_id { get; set; }
        public string quarter_nbr { get; set; }
        public string item_no { get; set; }
        public string department_code { get; set; }
        public string position_code { get; set; }
        public string rcrd_status { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by { get; set; }
    }
}
