//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla_reprocess_tbl
    {
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string empl_id { get; set; }
        public string item_no { get; set; }
        public string employment_status { get; set; }
        public string salary_grade { get; set; }
        public Nullable<byte> step_increment_cy { get; set; }
        public Nullable<byte> step_increment_ny { get; set; }
        public Nullable<System.DateTime> next_step_increment_eff_date { get; set; }
        public Nullable<decimal> step_increment_annual_amount { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> monthly_rate_ny { get; set; }
        public Nullable<System.DateTime> date_latest_appointment { get; set; }
        public Nullable<System.DateTime> effective_date_sg { get; set; }
        public Nullable<System.DateTime> effective_date_sg_ny { get; set; }
        public Nullable<decimal> annual_salary_cy { get; set; }
        public Nullable<decimal> annual_salary_ny { get; set; }
    }
}
