//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla22_position_override
    {
        public System.DateTime effectivity_date { get; set; }
        public string item_no { get; set; }
        public string employment_type { get; set; }
        public string position_title_override1 { get; set; }
        public string position_title_override2 { get; set; }
    }
}
