//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_panel_permanent_mbr_tbl
    {
        public string psb_user_id { get; set; }
        public string psb_first_name { get; set; }
        public string psb_last_name { get; set; }
        public string psb_middle_name { get; set; }
        public string psb_mbr_role { get; set; }
        public string psb_agency { get; set; }
        public Nullable<bool> psb_inhouse { get; set; }
        public Nullable<bool> active_status { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public Nullable<int> branch { get; set; }
    }
}
