//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicationvacant_hdr_tbl
    {
        public string ctrl_no { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string publish_at { get; set; }
        public Nullable<System.DateTime> publish_from { get; set; }
        public Nullable<System.DateTime> publish_to { get; set; }
        public string posted_in { get; set; }
    }
}
