//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rata_rate_sked_tbl
    {
        public string rate_type { get; set; }
        public int no_of_days_max { get; set; }
        public System.DateTime effective_date { get; set; }
        public Nullable<int> rate_percentage { get; set; }
    }
}
