//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reorg_appl_tbl
    {
        public string empl_id { get; set; }
        public string budget_code { get; set; }
        public string item_no_primary { get; set; }
        public string item_no_secondary { get; set; }
        public string item_no_tertiary { get; set; }
        public string appl_status { get; set; }
        public string acquired_item { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
