//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reorg_appl_not_qua_tbl
    {
        public string empl_id { get; set; }
        public string budget_code { get; set; }
        public string item_no { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
    }
}
