//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaries_tbl
    {
        public System.DateTime effective_date { get; set; }
        public string salary_grade { get; set; }
        public Nullable<decimal> monthly_step1 { get; set; }
        public Nullable<decimal> monthly_step2 { get; set; }
        public Nullable<decimal> monthly_step3 { get; set; }
        public Nullable<decimal> monthly_step4 { get; set; }
        public Nullable<decimal> monthly_step5 { get; set; }
        public Nullable<decimal> monthly_step6 { get; set; }
        public Nullable<decimal> monthly_step7 { get; set; }
        public Nullable<decimal> monthly_step8 { get; set; }
        public Nullable<decimal> daily_rate { get; set; }
        public Nullable<decimal> hourly_rate { get; set; }
        public string salary_grade_type { get; set; }
    }
}
