//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class securityaccessrolepages_tbl
    {
        public string role_id { get; set; }
        public string url_name { get; set; }
        public Nullable<bool> allow_add { get; set; }
        public Nullable<bool> allow_edit { get; set; }
        public Nullable<bool> allow_delete { get; set; }
        public Nullable<bool> allow_print { get; set; }
        public Nullable<bool> allow_view { get; set; }
    }
}
