//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicerecord_tbl
    {
        public string empl_id { get; set; }
        public int line_seq { get; set; }
        public Nullable<System.DateTime> period_from { get; set; }
        public Nullable<System.DateTime> period_to { get; set; }
        public string position_title { get; set; }
        public string employment_status { get; set; }
        public Nullable<decimal> salary_amount { get; set; }
        public string salary_type { get; set; }
        public string place_of_assignment { get; set; }
        public string agency_branch { get; set; }
        public Nullable<System.DateTime> separation_date { get; set; }
        public string separation_cause { get; set; }
        public string remarks_details { get; set; }
        public Nullable<bool> posted_data { get; set; }
        public string sr_type_code { get; set; }
        public Nullable<bool> exclude_in_gsis { get; set; }
    }
}
