//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signatories2_tbl
    {
        public System.DateTime effective_date { get; set; }
        public byte print_group { get; set; }
        public byte print_type { get; set; }
        public string name_of_signatory1 { get; set; }
        public string designation_of_signatory1 { get; set; }
        public string designation2_of_signatory1 { get; set; }
        public string name_of_signatory2 { get; set; }
        public string designation_of_signatory2 { get; set; }
        public string designation2_of_signatory2 { get; set; }
        public string name_of_signatory3 { get; set; }
        public string designation_of_signatory3 { get; set; }
        public string designation2_of_signatory3 { get; set; }
        public string name_of_signatory4 { get; set; }
        public string designation_of_signatory4 { get; set; }
        public string designation2_of_signatory4 { get; set; }
        public string print_purpose { get; set; }
    }
}
