//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffingplan_tbl
    {
        public string position_code { get; set; }
        public string department_code { get; set; }
        public string subdepartment_code { get; set; }
        public string division_code { get; set; }
        public string section_code { get; set; }
        public string general_function { get; set; }
        public string item_eduction { get; set; }
        public string item_work_experience { get; set; }
        public string item_training { get; set; }
        public string item_eligibility { get; set; }
        public string item_leadership_level1 { get; set; }
        public string item_leadership_level2 { get; set; }
        public string item_leadership_level3 { get; set; }
        public string item_leadership_level4 { get; set; }
        public string item_leadership_descr1 { get; set; }
        public string item_leadership_descr2 { get; set; }
        public string item_leadership_descr3 { get; set; }
        public string item_leadership_descr4 { get; set; }
        public string item_core_level1 { get; set; }
        public string item_core_level2 { get; set; }
        public string item_core_level3 { get; set; }
        public string item_core_level4 { get; set; }
        public string item_core_descr3 { get; set; }
        public string item_core_descr1 { get; set; }
        public string item_core_descr2 { get; set; }
        public string item_core_descr4 { get; set; }
        public string item_functional_level1 { get; set; }
        public string item_functional_level2 { get; set; }
        public string item_functional_level3 { get; set; }
        public string item_functional_level4 { get; set; }
        public string item_functional_descr1 { get; set; }
        public string item_functional_descr2 { get; set; }
        public string item_functional_descr3 { get; set; }
        public string item_functional_descr4 { get; set; }
        public string item_technical_level1 { get; set; }
        public string item_technical_level2 { get; set; }
        public string item_technical_level3 { get; set; }
        public string item_technical_level4 { get; set; }
        public string item_technical_descr1 { get; set; }
        public string item_technical_descr2 { get; set; }
        public string item_technical_descr3 { get; set; }
        public string item_technical_descr4 { get; set; }
        public string item_technical_percent1 { get; set; }
        public string item_technical_percent2 { get; set; }
        public string item_technical_percent3 { get; set; }
        public string item_technical_percent4 { get; set; }
    }
}
