//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tck_log_tbl
    {
        public string tck_nbr { get; set; }
        public string tck_description { get; set; }
        public string tck_details { get; set; }
        public string reported_user_id { get; set; }
        public Nullable<System.DateTime> reported_dttm { get; set; }
        public Nullable<byte> module_id { get; set; }
        public string tck_type { get; set; }
        public string tck_status { get; set; }
        public string assigned_user_id { get; set; }
        public Nullable<System.DateTime> assigned_dttm { get; set; }
        public Nullable<System.DateTime> resolved_dttm { get; set; }
        public string resolution_details { get; set; }
    }
}
