//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class technicalcompetency_dtl_tbl
    {
        public string techcom_ctrlno { get; set; }
        public string techcom_seq { get; set; }
        public string percent_worktime { get; set; }
        public string duties_responsibilities { get; set; }
        public string comlvl_code { get; set; }
    }
}
