//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class units_tbl
    {
        public System.DateTime effective_date { get; set; }
        public string unit_code { get; set; }
        public string unit_short_name { get; set; }
        public string unit_name1 { get; set; }
        public string unit_name2 { get; set; }
        public string department_code { get; set; }
        public string subdepartment_code { get; set; }
        public string division_code { get; set; }
        public string section_code { get; set; }
        public Nullable<int> sort_order_sect { get; set; }
        public string empl_id { get; set; }
        public string designation_head1 { get; set; }
        public string designation_head2 { get; set; }
    }
}
