//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cashadv_list
    {
        public string ca_ctrl_nbr { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string ca_voucher_nbr { get; set; }
        public string employment_type { get; set; }
        public string ca_short_descr { get; set; }
        public string post_status { get; set; }
        public string department_code { get; set; }
        public string fund_code { get; set; }
        public string docmnt_type { get; set; }
        public string voucher_nbr { get; set; }
        public string ca_status { get; set; }
        public string catype_code { get; set; }
    }
}
