//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cashadv_fund_sub_tbl_TRK
    {
        public string cafund_subcode { get; set; }
        public string cafund_subdescr { get; set; }
        public string cafund_bankname { get; set; }
        public string cafund_bankacct { get; set; }
        public string cafund_code { get; set; }
        public string cafund_descr { get; set; }
    }
}
