//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_deduction_accounts
    {
        public string deduc_code { get; set; }
        public string deduc_descr { get; set; }
        public string account_code { get; set; }
        public string account_sub_code { get; set; }
        public string employment_type { get; set; }
        public string accttype_code { get; set; }
        public string accttype_descr { get; set; }
        public string reference_field { get; set; }
    }
}
