//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_empl_jd_pos
    {
        public string empl_ctrl_nbr { get; set; }
        public string empl_id { get; set; }
        public string department_code { get; set; }
        public string department_name1 { get; set; }
        public string division_code { get; set; }
        public string division_name1 { get; set; }
        public string subdepartment_code { get; set; }
        public string section_code { get; set; }
        public string section_name1 { get; set; }
        public string position_code { get; set; }
        public string position_long_title { get; set; }
        public string employment_type { get; set; }
        public string employmenttype_description { get; set; }
        public string approval_status { get; set; }
        public string approval_status_descr { get; set; }
        public string approval_id { get; set; }
        public string action_x { get; set; }
    }
}
