//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_modules_assign_tbl
    {
        public byte module_id { get; set; }
        public string user_id { get; set; }
        public string employee_name { get; set; }
        public string assignment_type { get; set; }
    }
}
