//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrolldeduc_ledger_tbl_reseq
    {
        public string empl_id { get; set; }
        public string deduc_code { get; set; }
        public string row_nbr { get; set; }
        public string deduc_seq { get; set; }
        public Nullable<System.DateTime> deduc_date_from { get; set; }
        public Nullable<System.DateTime> deduc_date_to { get; set; }
        public string deduc_ref_nbr { get; set; }
        public Nullable<decimal> deduc_amount1 { get; set; }
    }
}
