//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrollregistry_dtl_othded_tbl_tax
    {
        public string payroll_registry_nbr { get; set; }
        public string empl_id { get; set; }
        public Nullable<decimal> other_ded_mand2 { get; set; }
        public string payroll_year { get; set; }
    }
}
