//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrollregistry_jo
    {
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string empl_id { get; set; }
        public Nullable<double> nod_work_1st { get; set; }
        public Nullable<double> days_worked { get; set; }
        public Nullable<double> hours_worked { get; set; }
        public Nullable<decimal> nbr_days_absent { get; set; }
        public Nullable<decimal> hours_ot { get; set; }
        public Nullable<decimal> hours_sal { get; set; }
    }
}
