//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_phic_share_employees_list
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public Nullable<decimal> empl_no_share { get; set; }
        public string period_covered { get; set; }
        public string position_long_title { get; set; }
        public string department_name1 { get; set; }
        public Nullable<decimal> salary_rate_amt { get; set; }
        public string salary_rate_descr { get; set; }
        public string group_code { get; set; }
        public string group_description { get; set; }
        public string group_class { get; set; }
        public string group_class_descr { get; set; }
    }
}
