//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrollemployee_tax_dtl_tbl_ACT
    {
        public System.DateTime effective_date { get; set; }
        public string empl_id { get; set; }
        public string voucher_nbr { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string payrolltemplate_code { get; set; }
        public string payrolltemplate_descr { get; set; }
        public string payroll_period_descr { get; set; }
        public Nullable<decimal> pera_ca_amt { get; set; }
        public Nullable<decimal> gsis_ps { get; set; }
        public Nullable<decimal> phic_ps { get; set; }
        public Nullable<decimal> hdmf_ps { get; set; }
        public Nullable<decimal> hazard_pay { get; set; }
        public Nullable<decimal> subsistence_allowance { get; set; }
        public Nullable<decimal> laundry_allowance { get; set; }
        public Nullable<decimal> gross_pay { get; set; }
        public Nullable<decimal> wtax_amt { get; set; }
        public string remarks { get; set; }
        public string rcrd_status { get; set; }
        public string acctclass_code { get; set; }
    }
}
