//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_personnel_lnd_tbl
    {
        public int seq_no { get; set; }
        public string empl_id { get; set; }
        public string learn_devt_title { get; set; }
        public string learn_devt_type { get; set; }
        public string conducted_by { get; set; }
        public string learn_devt_from { get; set; }
        public string learn_devt_fromS { get; set; }
        public string learn_devt_to { get; set; }
        public double no_of_hrs { get; set; }
    }
}
