//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_phic_diff_4_perc_re_ce
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public Nullable<int> payroll_month { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> gsis_ps_payroll { get; set; }
        public Nullable<decimal> phic_gs_3perc { get; set; }
        public Nullable<decimal> phic_ps_3perc { get; set; }
        public Nullable<decimal> philhealth_4perc { get; set; }
        public Nullable<decimal> philhealth_ps_4perc { get; set; }
        public Nullable<decimal> phic_gs_diff { get; set; }
        public Nullable<decimal> phic_ps_diff { get; set; }
    }
}
