//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrollregistry_info3_HRIS_PAY
    {
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string payrolltemplate_code { get; set; }
        public string employment_type { get; set; }
        public string payroll_group_nbr { get; set; }
        public string payroll_registry_descr { get; set; }
        public Nullable<System.DateTime> payroll_period_from { get; set; }
        public Nullable<System.DateTime> payroll_period_to { get; set; }
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix_name { get; set; }
        public string rate_basis { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> daily_rate { get; set; }
        public Nullable<decimal> hourly_rate { get; set; }
        public Nullable<decimal> pera_amt { get; set; }
        public Nullable<decimal> gsis_gs { get; set; }
        public Nullable<decimal> gsis_ps { get; set; }
        public Nullable<decimal> sif_gs { get; set; }
        public Nullable<decimal> hdmf_gs { get; set; }
        public Nullable<decimal> hdmf_ps { get; set; }
        public Nullable<decimal> phic_gs { get; set; }
        public Nullable<decimal> phic_ps { get; set; }
        public Nullable<decimal> wtax { get; set; }
        public Nullable<decimal> wtax_2perc { get; set; }
        public Nullable<decimal> wtax_3perc { get; set; }
        public Nullable<decimal> wtax_5perc { get; set; }
        public Nullable<decimal> wtax_8perc { get; set; }
        public Nullable<decimal> wtax_10perc { get; set; }
        public Nullable<decimal> wtax_15perc { get; set; }
        public Nullable<decimal> gsis_uoli { get; set; }
        public Nullable<decimal> gsis_uoli45 { get; set; }
        public Nullable<decimal> gsis_uoli50 { get; set; }
        public Nullable<decimal> gsis_uoli55 { get; set; }
        public Nullable<decimal> gsis_uoli60 { get; set; }
        public Nullable<decimal> gsis_uoli65 { get; set; }
        public Nullable<decimal> nhmfc_hsing { get; set; }
        public Nullable<decimal> nafc_svlf { get; set; }
        public Nullable<decimal> sss_ps { get; set; }
        public Nullable<decimal> hdmf_ps2 { get; set; }
        public Nullable<decimal> hdmf_mp2 { get; set; }
        public Nullable<decimal> philamlife_ps { get; set; }
        public Nullable<decimal> gsis_ehp { get; set; }
        public Nullable<decimal> gsis_hip { get; set; }
        public Nullable<decimal> gsis_ceap { get; set; }
        public Nullable<decimal> gsis_addl_ins { get; set; }
        public Nullable<decimal> other_premium1 { get; set; }
        public Nullable<decimal> other_premium2 { get; set; }
        public Nullable<decimal> other_premium3 { get; set; }
        public Nullable<decimal> other_premium4 { get; set; }
        public Nullable<decimal> other_premium5 { get; set; }
        public Nullable<decimal> gsis_conso_ln { get; set; }
        public Nullable<decimal> gsis_policy_reg_ln { get; set; }
        public Nullable<decimal> gsis_policy_opt_ln { get; set; }
        public Nullable<decimal> gsis_uoli_ln { get; set; }
        public Nullable<decimal> gsis_emergency_ln { get; set; }
        public Nullable<decimal> gsis_ecard_ln { get; set; }
        public Nullable<decimal> gsis_educ_asst_ln { get; set; }
        public Nullable<decimal> gsis_real_state_ln { get; set; }
        public Nullable<decimal> gsis_sos_ln { get; set; }
        public Nullable<decimal> gsis_help { get; set; }
        public Nullable<decimal> gsis_housing_ln { get; set; }
        public Nullable<decimal> hdmf_mpl_ln { get; set; }
        public Nullable<decimal> hdmf_hse_ln { get; set; }
        public Nullable<decimal> hdmf_cal_ln { get; set; }
        public Nullable<decimal> hdmf_loyalty_card { get; set; }
        public Nullable<decimal> nico_ln { get; set; }
        public Nullable<decimal> network_ln { get; set; }
        public Nullable<decimal> ccmpc_ln { get; set; }
        public Nullable<decimal> other_loan1 { get; set; }
        public Nullable<decimal> other_loan2 { get; set; }
        public Nullable<decimal> other_loan3 { get; set; }
        public Nullable<decimal> other_loan4 { get; set; }
        public Nullable<decimal> other_loan5 { get; set; }
        public Nullable<decimal> uniform_amt { get; set; }
        public Nullable<decimal> bir_tax { get; set; }
        public string payroll_source { get; set; }
        public string payrolltemplate_descr { get; set; }
        public Nullable<decimal> gross_pay { get; set; }
        public Nullable<decimal> net_pay { get; set; }
        public Nullable<decimal> net_pay1 { get; set; }
        public Nullable<decimal> net_pay2 { get; set; }
        public Nullable<double> lwpay_day { get; set; }
        public Nullable<double> lowpay_day { get; set; }
        public Nullable<decimal> lowp_amount { get; set; }
        public Nullable<decimal> lowp_amount_pera { get; set; }
        public Nullable<double> lates_mins_hrs { get; set; }
        public Nullable<decimal> lates_amount { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> leave_earned { get; set; }
        public decimal lates_amount_pera { get; set; }
        public decimal lwpay_day_spl { get; set; }
        public Nullable<decimal> qa_amount { get; set; }
        public Nullable<decimal> ra_amount { get; set; }
        public Nullable<decimal> ta_amount { get; set; }
        public Nullable<decimal> cash_gift_amt { get; set; }
        public Nullable<decimal> hazard_pay { get; set; }
        public Nullable<decimal> subsistence_pay { get; set; }
        public Nullable<decimal> laundry_pay { get; set; }
        public decimal wages_amt { get; set; }
    }
}
