//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_phic_share_ledger_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string department_code { get; set; }
        public string department_name1 { get; set; }
        public string period_from { get; set; }
        public string period_to { get; set; }
        public string period_covered { get; set; }
        public Nullable<decimal> share_amt { get; set; }
        public Nullable<decimal> med_perc { get; set; }
        public Nullable<decimal> nonmed_perc { get; set; }
        public string ledger_status { get; set; }
        public string ledger_status_descr { get; set; }
        public string created_by_user_id { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string updated_by_user_id { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
