//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrollemployeemaster_min_max
    {
        public string empl_id { get; set; }
        public Nullable<System.DateTime> min_effective_date { get; set; }
        public Nullable<System.DateTime> max_effective_date { get; set; }
    }
}
