//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_personnel_workexprnce2_tbl
    {
        public int seq_no { get; set; }
        public string empl_id { get; set; }
        public string workexp_from { get; set; }
        public string workexp_fromS { get; set; }
        public string workexp_to { get; set; }
        public string position_title { get; set; }
        public string dept_agncy_offc_co { get; set; }
        public decimal monthly_salary { get; set; }
        public string salary_job_grade { get; set; }
        public string appt_status { get; set; }
        public bool gov_srvc { get; set; }
        public string printing_date { get; set; }
    }
}
