//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_placement_reorg_appl_list
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string employee_name_format2 { get; set; }
        public string budget_code { get; set; }
        public string item_no_primary { get; set; }
        public string item_no_secondary { get; set; }
        public string item_no_tertiary { get; set; }
        public string item_no_primary_descr { get; set; }
        public string item_no_secondary_descr { get; set; }
        public string item_no_tertiary_descr { get; set; }
        public string appl_status { get; set; }
        public string acquired_item { get; set; }
        public string acquired_item_descr { get; set; }
        public System.DateTime created_dttm { get; set; }
        public System.DateTime updated_dttm { get; set; }
        public string position_code { get; set; }
        public string item_no { get; set; }
        public string employment_type { get; set; }
        public string position_title1 { get; set; }
        public string position_title2 { get; set; }
        public string position_short_title { get; set; }
        public string position_long_title { get; set; }
        public string salary_grade { get; set; }
        public string qs_eduction { get; set; }
        public string qs_work_experience { get; set; }
        public string qs_training { get; set; }
        public string qs_eligibility { get; set; }
        public string department_code { get; set; }
        public string department_name1 { get; set; }
        public string department_name2 { get; set; }
        public string department_short_name { get; set; }
        public string department_proper_name { get; set; }
    }
}
