//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payroll_rep_signatories
    {
        public string payroll_group_nbr { get; set; }
        public string special_group { get; set; }
        public string repsig_dept_name_grp { get; set; }
        public string repsig_dept_desig_grp { get; set; }
        public string repsig_dept_name { get; set; }
        public string repsig_dept_desig { get; set; }
        public string repsig_pacco_name { get; set; }
        public string repsig_pacco_desig { get; set; }
        public string repsig_pto_name { get; set; }
        public string repsig_pto_desig { get; set; }
        public string repsig_pbo_name { get; set; }
        public string repsig_pbo_desig { get; set; }
        public string repsig_gov_name { get; set; }
        public string repsig_gov_desig { get; set; }
        public string repsig_coa_name { get; set; }
        public string repsig_coa_desig { get; set; }
        public string org_name { get; set; }
        public string org_name1 { get; set; }
        public string org_name2 { get; set; }
        public string org_address1 { get; set; }
        public string org_address2 { get; set; }
        public string org_address3 { get; set; }
        public string org_address4 { get; set; }
    }
}
