//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_pds_page3
    {
        public string seq_no { get; set; }
        public string empl_id { get; set; }
        public string descr { get; set; }
        public string other_type { get; set; }
        public string printing_date { get; set; }
    }
}
