//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_personneladdresses_tbl
    {
        public string empl_id { get; set; }
        public string houselot_nbr { get; set; }
        public string street { get; set; }
        public string purok { get; set; }
        public string barangay_name { get; set; }
        public string municipality_name { get; set; }
        public string province_name { get; set; }
        public string zip_code { get; set; }
        public string address_type { get; set; }
        public string province_code { get; set; }
        public string municipality_code { get; set; }
        public string barangay_code { get; set; }
    }
}
