//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrollemployeemaster_tbl_ref_list_all
    {
        public string empl_id { get; set; }
        public string account_code { get; set; }
        public string account_sub_code { get; set; }
        public string id_nbr_type { get; set; }
        public string account_id_nbr_ref { get; set; }
    }
}
