//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_pds_page1
    {
        public string empl_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix_name { get; set; }
        public string courtisy_title { get; set; }
        public string postfix_name { get; set; }
        public string birth_date { get; set; }
        public bool citizenship_type { get; set; }
        public bool citizenship_nature { get; set; }
        public string citizenship_country { get; set; }
        public string birth_place { get; set; }
        public string gender { get; set; }
        public string gender_descr { get; set; }
        public string civil_status { get; set; }
        public string civil_status_descr { get; set; }
        public string emp_height { get; set; }
        public string emp_weight { get; set; }
        public string blood_type { get; set; }
        public string gsis_id_no { get; set; }
        public string hdmf_id_no { get; set; }
        public string phic_id_no { get; set; }
        public string sss_id_no { get; set; }
        public string bir_tin { get; set; }
        public string spouse_last_name { get; set; }
        public string spouse_first_name { get; set; }
        public string spouse_middle_name { get; set; }
        public string spouse_suffix_name { get; set; }
        public string spouse_occupation { get; set; }
        public string spouse_employer_name { get; set; }
        public string spouse_business_address { get; set; }
        public string spouse_tel_no { get; set; }
        public string father_last_name { get; set; }
        public string father_middle_name { get; set; }
        public string father_first_name { get; set; }
        public string father_suffix_name { get; set; }
        public string mother_last_name { get; set; }
        public string mother_middle_name { get; set; }
        public string mother_first_name { get; set; }
        public string houselot_nbr_00 { get; set; }
        public string street_00 { get; set; }
        public string purok_00 { get; set; }
        public string barangay_name_00 { get; set; }
        public string municipality_name_00 { get; set; }
        public string province_name_00 { get; set; }
        public string zip_code_00 { get; set; }
        public string houselot_nbr_01 { get; set; }
        public string street_01 { get; set; }
        public string purok_01 { get; set; }
        public string barangay_name_01 { get; set; }
        public string municipality_name_01 { get; set; }
        public string province_name_01 { get; set; }
        public string zip_code_01 { get; set; }
        public string tel_no { get; set; }
        public string mobile_no { get; set; }
        public string email_add { get; set; }
        public string school_name_01 { get; set; }
        public string basic_educ_deg_01 { get; set; }
        public string period_from_01 { get; set; }
        public string period_to_01 { get; set; }
        public string highest_lvl_earned_01 { get; set; }
        public string year_graduated_01 { get; set; }
        public string schlr_acdmic_rcvd_01 { get; set; }
        public string school_name_02 { get; set; }
        public string basic_educ_deg_02 { get; set; }
        public string period_from_02 { get; set; }
        public string period_to_02 { get; set; }
        public string highest_lvl_earned_02 { get; set; }
        public string year_graduated_02 { get; set; }
        public string schlr_acdmic_rcvd_02 { get; set; }
        public string school_name_03 { get; set; }
        public string basic_educ_deg_03 { get; set; }
        public string period_from_03 { get; set; }
        public string period_to_03 { get; set; }
        public string highest_lvl_earned_03 { get; set; }
        public string year_graduated_03 { get; set; }
        public string schlr_acdmic_rcvd_03 { get; set; }
        public string school_name_04 { get; set; }
        public string basic_educ_deg_04 { get; set; }
        public string period_from_04 { get; set; }
        public string period_to_04 { get; set; }
        public string highest_lvl_earned_04 { get; set; }
        public string year_graduated_04 { get; set; }
        public string schlr_acdmic_rcvd_04 { get; set; }
        public string school_name_05 { get; set; }
        public string basic_educ_deg_05 { get; set; }
        public string period_from_05 { get; set; }
        public string period_to_05 { get; set; }
        public string highest_lvl_earned_05 { get; set; }
        public string year_graduated_05 { get; set; }
        public string schlr_acdmic_rcvd_05 { get; set; }
        public string school_name_011 { get; set; }
        public string basic_educ_deg_011 { get; set; }
        public string period_from_011 { get; set; }
        public string period_to_011 { get; set; }
        public string highest_lvl_earned_011 { get; set; }
        public string year_graduated_011 { get; set; }
        public string schlr_acdmic_rcvd_011 { get; set; }
        public string school_name_022 { get; set; }
        public string basic_educ_deg_022 { get; set; }
        public string period_from_022 { get; set; }
        public string period_to_022 { get; set; }
        public string highest_lvl_earned_022 { get; set; }
        public string year_graduated_022 { get; set; }
        public string schlr_acdmic_rcvd_022 { get; set; }
        public string school_name_033 { get; set; }
        public string basic_educ_deg_033 { get; set; }
        public string period_from_033 { get; set; }
        public string period_to_033 { get; set; }
        public string highest_lvl_earned_033 { get; set; }
        public string year_graduated_033 { get; set; }
        public string schlr_acdmic_rcvd_033 { get; set; }
        public string school_name_044 { get; set; }
        public string basic_educ_deg_044 { get; set; }
        public string period_from_044 { get; set; }
        public string period_to_044 { get; set; }
        public string highest_lvl_earned_044 { get; set; }
        public string year_graduated_044 { get; set; }
        public string schlr_acdmic_rcvd_044 { get; set; }
        public string school_name_055 { get; set; }
        public string basic_educ_deg_055 { get; set; }
        public string period_from_055 { get; set; }
        public string period_to_055 { get; set; }
        public string highest_lvl_earned_055 { get; set; }
        public string year_graduated_055 { get; set; }
        public string schlr_acdmic_rcvd_055 { get; set; }
        public string printing_date { get; set; }
    }
}
