//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_temp_phic_jo_3MONS
    {
        public string empl_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix_name { get; set; }
        public string employee_name { get; set; }
        public string department_short_name { get; set; }
        public decimal gross_pay_mar { get; set; }
        public decimal gross_pay_apr { get; set; }
        public decimal gross_pay_may { get; set; }
        public decimal phic_ps_mar { get; set; }
        public decimal phic_ps_apr { get; set; }
        public decimal phic_ps_may { get; set; }
        public Nullable<decimal> phic_ps_new_mar { get; set; }
        public Nullable<decimal> phic_ps_new_apr { get; set; }
        public Nullable<decimal> phic_ps_new_may { get; set; }
        public Nullable<decimal> salary_flooring_amt { get; set; }
        public Nullable<decimal> salary_ceiling_amt { get; set; }
        public Nullable<decimal> flooring_amt { get; set; }
        public Nullable<decimal> ceiling_amt { get; set; }
    }
}
