//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_training_info_tbl_list
    {
        public string train_code { get; set; }
        public string train_descr { get; set; }
        public string train_descr_short { get; set; }
        public string train_details { get; set; }
        public string train_link { get; set; }
        public string train_mode { get; set; }
        public string train_mode_descr { get; set; }
        public string train_type_descr { get; set; }
        public string train_type { get; set; }
        public string train_dt_fr { get; set; }
        public string train_dt_to { get; set; }
        public string train_dt_completion { get; set; }
        public string train_required { get; set; }
        public string train_required_descr { get; set; }
        public string train_coverage { get; set; }
        public string train_coverage_descr { get; set; }
        public string rcrd_status { get; set; }
        public string rcrd_status_descr { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
