//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_temp_sra_3MONS
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public decimal sept_nbr_days { get; set; }
        public decimal sept_net_pay { get; set; }
        public decimal oct_nbr_days { get; set; }
        public decimal oct_net_pay { get; set; }
        public decimal nov_nbr_days { get; set; }
        public decimal nov_net_pay { get; set; }
        public decimal dec_nbr_pay { get; set; }
        public decimal dec_net_pay { get; set; }
        public string employment_type { get; set; }
        public string employment_type_descr { get; set; }
        public string department_short_name { get; set; }
    }
}
