//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_training_empl_tbl_list_not_started
    {
        public string empl_id { get; set; }
        public string train_dt_completed { get; set; }
        public string empl_train_status { get; set; }
        public string empl_train_status_descr { get; set; }
        public string train_code { get; set; }
        public string train_descr { get; set; }
        public string train_descr_short { get; set; }
        public string train_details { get; set; }
        public string train_mode { get; set; }
        public string train_mode_descr { get; set; }
        public string train_type_descr { get; set; }
        public string train_type { get; set; }
        public string train_filename_vid { get; set; }
        public string train_filename_pdf { get; set; }
        public string train_coverage { get; set; }
        public string train_coverage_descr { get; set; }
        public string rcrd_status { get; set; }
        public string rcrd_status_descr { get; set; }
        public Nullable<int> train_year { get; set; }
        public Nullable<int> train_month { get; set; }
        public string train_dt_4completion { get; set; }
        public string train_link { get; set; }
    }
}
