//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eSelfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_temp_sss_jo_3MONS
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public decimal sss_jan { get; set; }
        public decimal sss_feb { get; set; }
        public decimal sss_mar { get; set; }
    }
}
